cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE
        "${CMAKE_SOURCE_DIR}/external/vcpkg/scripts/buildsystems/vcpkg.cmake"
        CACHE STRING "Vcpkg toolchain file")
endif()

project(SoulSync LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(BUILD_GL OFF CACHE BOOL "" FORCE)
set(BUILD_GLES2 OFF CACHE BOOL "" FORCE)
set(BUILD_GLES3 OFF CACHE BOOL "" FORCE)
set(USE_OPENGL OFF CACHE BOOL "" FORCE)
set(LIBMGBA_ONLY ON CACHE BOOL "" FORCE)
set(BUILD_GBA ON CACHE BOOL "" FORCE)
set(BUILD_GB OFF CACHE BOOL "" FORCE)
set(BUILD_SDL OFF CACHE BOOL "" FORCE)
set(BUILD_QT OFF CACHE BOOL "" FORCE)
set(ENABLE_VFS ON CACHE BOOL "" FORCE)
set(ENABLE_DIRECTORIES ON CACHE BOOL "" FORCE)

add_subdirectory(external/mgba)
add_subdirectory(client)